apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: nullclaw-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: agents
      images:
        - alias: nullclaw
          imageName: ghcr.io/bapttf/nullclaw-lou-config/nullclaw-custom
          commonUpdateSettings:
            updateStrategy: latest
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"
    gitConfig:
      branch: main
