apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: voyage-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: voyage
      images:
        - alias: voyage-app
          imageName: ghcr.io/rjullien/voyage-app
          commonUpdateSettings:
            pullSecret: pullsecret:voyage/ghcr-login-secret
            updateStrategy: newest-build
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"
    gitConfig:
      branch: main
      writeBackTarget: "kustomization:./workloads/voyage"
