# Tailscale OAuth credentials from Infisical
# Configure in Infisical after Infisical is deployed:
#   - project: infrastructure
#   - environment: production
#   - secret path: /tailscale
#   - keys: client-id, client-secret

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tailscale-credentials
  namespace: tailscale
  annotations:
      argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      secretsScope:
        projectId: 6d765684-e2f5-4f07-afb1-4965994c9c04
        envSlug: production
        secretsPath: /tailscale
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: operator-oauth
      secretNamespace: tailscale
      secretType: Opaque
      creationPolicy: Owner
