apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    size: 2Gi
  managed:
    roles:
      - connectionLimit: -1	
        ensure: present	
        inherit: true
        name: forgejo
        login: true
        passwordSecret:
          name: forgejo-db-secret
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: jujudb
        login: true
        passwordSecret:
          name: jujudb-db-secret
