apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: forgejo-db-credentials-cnpg
  namespace: cnpg-system
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /forgejo/db
        secretName: password
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: forgejo-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner