apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: forgejo-db-credentials-cnpg
  namespace: cnpg-system
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /forgejo/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: forgejo-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: jujudb-db-credentials-cnpg
  namespace: cnpg-system
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /jujudb/db # À adapter si tu as créé un dossier spécifique pour la DB
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: jujudb-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: lacoope-db-credentials-cnpg
  namespace: cnpg-system
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /lacoope/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: lacoope-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openwebui-db-credentials-cnpg
  namespace: cnpg-system
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /openwebui/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: openwebui-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner