apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo-db
  namespace: cnpg-system
spec:
  name: forgejo
  owner: forgejo
  cluster:
    name: postgres-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jujudb-db
  namespace: cnpg-system
spec:
  name: jujudb
  owner: jujudb
  cluster:
    name: postgres-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lacoope-db
  namespace: cnpg-system
spec:
  name: lacoope
  owner: lacoope
  cluster:
    name: postgres-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openwebui-db
  namespace: cnpg-system
spec:
  name: openwebui
  owner: openwebui
  cluster:
    name: postgres-cluster