apiVersion: v1
kind: Service
metadata:
  name: hermes-lea
  namespace: openclaw
  labels:
    app: hermes-lea
spec:
  selector:
    app: hermes-lea
  ports:
    - protocol: TCP
      port: 8642
      targetPort: http
      name: http
    - protocol: TCP
      port: 9119
      targetPort: dashboard
      name: dashboard
