apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - infisical-secret.yaml
  - hermes-lea-pvc.yaml
  - hermes-lea-deployment.yaml
  - hermes-lea-service.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: hermes-lea-config
    files:
      - config.yaml=config.yaml
