apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: lacoope-backend-secrets
  namespace: lacoope
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /lacoope
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: lacoope-backend-secret
      secretNamespace: lacoope
      secretType: Opaque
      creationPolicy: Owner
