apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw
  labels:
    app: openclaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openclaw
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # spin up new pod before killing old one
      maxUnavailable: 0   # old pod stays up until new pod is Ready
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      containers:
        - name: openclaw
          image: ghcr.io/bapttf/openclaw-lea-config:sha-fc206971247864a58ed608d73a1ba2e4e638559a
          resources:
            requests:
              cpu: "50m"
              memory: "512Mi"
            limits:
              cpu: "2000m"         
              memory: "3Gi"
          ports:
            - containerPort: 22
              name: ssh
            # - containerPort: 18789
            #   name: gateway
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 18789
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 18789
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          envFrom:
            - secretRef:
                name: openclaw-secret
          env:
            - name: OPENCLAW_SSH_ENABLED
              value: "true"
            - name: OPENCLAW_SSH_PORT
              value: "22"
            - name: OPENCLAW_CONFIG_PATH
              value: "/home/node/.openclaw/lea/openclaw.json"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1280 --max-semi-space-size=16"
          volumeMounts:
            - name: openclaw-home
              mountPath: /home
      securityContext:
        fsGroup: 1000
      volumes:
        - name: openclaw-home
          persistentVolumeClaim:
            claimName: openclaw-home-pvc