apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw

resources:
  - agents-rbac
  - openclaw
  - hermes
  - grokbot
  - hermes-lya
  - hermes-lya-filebrowser
  - kirocrew
  - bifrost
  - camofox
  - searxng
