apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw

resources:
  - openclaw
  - nullclaw
  - hermes-leo
  - hermes-lya
  - hermes-lya-filebrowser
  - bifrost
  - camofox
  - cours-ia
