apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - infisical-secret.yaml
  - hermes-leo-pvc.yaml
  - hermes-leo-deployment.yaml
  - hermes-leo-service.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: hermes-leo-config
    files:
      - config.yaml=config.yaml
