apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - nullclaw-pvc.yaml
  - nullclaw-deployment.yaml
  - nullclaw-service.yaml

configMapGenerator:
  - name: nullclaw-config
    files:
      - config.json=nullclaw_config.json
  - name: lou-ssh-config
    files:
      - config=ssh_config
