apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - bifrost-deployment.yaml
  - bifrost-service.yaml
  - bifrost-ingress.yaml

configMapGenerator:
  - name: bifrost-config
    files:
      - config.json=bifrost_config.json