---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-db-credentials
  namespace: infisical
spec:
  encryptedData:
    password: AgCOwn5sp7BIK8rp81Rk3TfplzA8Q/bfaOwKa28aDnP2OrVtPmULjZ4y5UBvHvxA31oc0FthCYlMvRLk4c0YFKqHIhOt43IPKNJAtaYgZNj++2wBEesAfmZ5zF0qnJ1sMX/uJ34nUungNt5xzVSOaBglPH141K0cbBaoFxKwZ1U7NHbJVo14+Nwno0wK7SpyFUOyhdBluUYLHe+tXdaf2XGSAHqGw8sqw0ba3ooqUXNwAr6KqfzvsR7Smyhtgol3FwZQx5/y04Fc1tStgetIOPVkPcEGgbGzgkfPDhl3HC1Ga5dGHAa3jTBCiCr6mZhmK+pQ8VHcsZJohGdMbpgeJoNmlLldCjcaggdSl2dFR9iOTamKE5NqN39oFZBaPeMM/K29a39icePlpSu2fUc/LXopjuu7aY4ije7DNrBk0EvO2o5fxzHVVNo7ipbZftE8fs4Ddg7BLmCqn1soFCqxdFszyKh4jKeFE/VKkEQDaKPwJ4Kna51elN6U694AewAVdZq3oxCLwc4BFs6674V26MfPUtwdzREHy6CiO5nUsLLZTiD3f1UYh+FsRPA3cpu6rIrBKjpqxErk4t7lec5c5pO2Z9Rr/9AX+5R7UaO0iDgzrH7bBK/yh+7VFa7gcpYL/gSbqzOOKnR0HSQgAanlGj83YCqHyJF70ZeiMk3Hq1NL7wq0SwxoQSGTx+CHI18cliSq0PHpD6AFJz/x3SWdWyqpFpQ=
    username: AgAumu7gwPIWpZelZqf2iIpSIhzt6cqyek3/VgyeF0z26XeWSt0B0oG+YMS96nFeKUC3UMbIsC/zLIAlDLAF10jlCm8IOuO+uxc3sSG59I8dqXSF/i5IuMEy5kNZLRVkhfhLXlyJQlfrrZ6KQZw2E8sCY4MlmwHKXuVjHN8pzvUtg992qumWT6AgBgyn3J8jgb8s60c04mwgZOWYhOguVp3GiJlZJDza2sSdUNK2O3PUEyDsKfM2Dr9cp9jtosBj2wMB91YWiepP9aXBpOfcnlPsYV8ErcbihHpg9wW9Gj1MKfYaBWrVcMFeQ4Fbc1x+9UPc0ygvpv63ZJYiLI8Bu+/ne0Oq+6chBpamSzl+h2P3zdDRM3TekT1J3jIWOBfNYlUcoEA7r+m937vCeoAP8KK+H42PldGJh3XPSIsLpDZaPpboYabzp8WFDLu+ew1iutOC73+dcpZ/SdB5t+TD8VJ15mHUtmjb5hZN3r6fMzRuPb/Qvd8iZIjUpxxQKIqfKerlNKwWVbZFA7n7CRcGyk83g5JDGHK6ZWDTB87kJZG4exdLu1jZEsJuCILUg3ihvJna1rUkMJumd6+YjN0VVWherDxXkljm2M8iMuXzmX+W1noVkh7G/dNstN/EbFXxmHenafncBz1igUEz1Gs+U7+Qmsn5/9ucNdRtrynZbDGT+g6kaAmKDdDYaFLetytjxryAdneEBr3VPXY=
  template:
    metadata:
      name: infisical-db-credentials
      namespace: infisical
    type: Opaque
