# -- Overrides the default release name
nameOverride: ""

# -- Overrides the full name of the release, affecting resource names
fullnameOverride: ""

infisical:
  # -- Enable Infisical chart deployment
  enabled: true
  # -- Sets the name of the deployment within this chart
  name: infisical

  autoBootstrap:
    enabled: false
    image:
      tag: "0.41.86"
    secretTemplate: '{"data":{"token":"{{.Identity.Credentials.Token}}"}}'
    secretDestination:
      name: "infisical-bootstrap-secret"
      namespace: "default"
    organization: "default-org"
    credentialSecret:
      name: "infisical-bootstrap-credentials"

  databaseSchemaMigrationJob:
    image:
      repository: ghcr.io/groundnuty/k8s-wait-for
      tag: no-root-v2.0
      pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    annotations: {}
    name: null

  fullnameOverride: ""
  podAnnotations: {}
  deploymentAnnotations: {}
  
  replicaCount: 1

  image:
    repository: infisical/infisical
    tag: "v0.151.0"
    pullPolicy: IfNotPresent
    imagePullSecrets: []

  affinity: {}
  tolerations: []
  nodeSelector: {}
  topologySpreadConstraints: []

  kubeSecretRef: "infisical-secrets"

  service:
    annotations: {}
    type: ClusterIP
    nodePort: ""

  extraEnv: []

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"

ingress:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false