apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/'
    chart: infisical-standalone
    # It is highly recommended to pin this to a specific chart version in production
    targetRevision: '*' 
    helm:
      valueFiles:
        - '$values/workloads/infisical/values.yaml'
  - repoURL: 'https://github.com/BaptTF/vps-infra.git' 
    targetRevision: HEAD
    # The 'ref' creates the '$values' variable used in the first source
    ref: values
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true