apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/'
    chart: infisical-standalone
    # It is highly recommended to pin this to a specific chart version in production
    targetRevision: '*' 
    helm:
      values: |
        # Disable the chart's built-in Ingress since you provided a Traefik IngressRoute
        ingress:
          enabled: false
        
        infisical:
          image:
            repository: infisical/infisical
            tag: "v0.151.0"  # Check https://hub.docker.com/r/infisical/infisical/tags for latest
            pullPolicy: IfNotPresent
          replicaCount: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true