apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-livesync
  namespace: couchdb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`couchdb.192.168.122.133.nip.io`)
      kind: Rule
      services:
        # Matches the fullnameOverride service name
        - name: couchdb
          port: 5984
  tls: {}