apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: couchdb

# This inflates the official CouchDB Helm chart
helmCharts:
  - name: couchdb
    repo: https://apache.github.io/couchdb-helm
    version: 4.6.3 # Use the latest stable version
    releaseName: couchdb
    namespace: couchdb
    valuesFile: values.yaml

resources:
  - couchdb-infisical-secret.yaml
  - ingress-tailscale.yaml
  - ingress-route.yaml