apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kirocrew-cert
  namespace: openclaw
spec:
  secretName: kirocrew-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "kirocrew.bapttf.com"
