server:
  port: 80
  cacheDir: /home/filebrowser/data/tmp
  externalUrl: "https://lya-drive.bapttf.com"
  sources:
    - path: /srv/data
      config:
        defaultEnabled: true
        defaultUserScope: "/"
        rules:
          - ignoreHidden: false
auth:
  adminUsername: baptiste
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
    password:
      enabled: false
      minLength: 0
userDefaults:
  account:
    loginMethod: proxy
    scope: "/"
    permissions:
      admin: false
      modify: true
      share: true
      download: true
      create: true
      delete: true
      api: false
      realtime: true
http:
  trustedHeaders:
    - X-Forwarded-For
    - X-Real-IP
