# Pull Admin Credentials from Infisical
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: forgejo-admin-credentials
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /forgejo/admin
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: forgejo-admin-secret
      secretNamespace: forgejo
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: forgejo-admin-credentials
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /forgejo/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: forgejo-admin-secret
      secretNamespace: forgejo
      secretType: Opaque
      creationPolicy: Owner