apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - forgejo-infisical-secret.yaml
  - forgejo-ssh-ingress.yaml

helmCharts:
  - name: forgejo
    # Kustomize supports OCI registries for Helm
    repo: oci://code.forgejo.org/forgejo-helm
    version: 16.2.0 # Update this to your desired version
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml