ingress:
  enabled: true
  className: traefik
  hosts:
    - host: git.192.168.122.133.nip.io
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  storageClass: "local-path"
  size: 10Gi

# Disable bundled DBs
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis:
  enabled: false

gitea:
  admin:
    existingSecret: forgejo-admin-secret
    
  additionalConfigSources:
    - secret:
        secretName: forgejo-db-secret
  config:
    server:
      DOMAIN: git.192.168.122.133.nip.io
      ROOT_URL: "http://git.192.168.122.133.nip.io/"
      SSH_DOMAIN: git.192.168.122.133.nip.io
      SSH_PORT: 22
      SSH_LISTEN_PORT: 22
