ingress:
  enabled: true
  className: traefik
  hosts:
    - host: git.bapttf.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - git.bapttf.com
      secretName: tls-certificate

persistence:
  enabled: true
  storageClass: "local-path"
  size: 10Gi

# Disable bundled DBs
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis:
  enabled: false

gitea:
  admin:
    existingSecret: forgejo-admin-secret
    
  additionalConfigSources:
    - secret:
        secretName: forgejo-db-secret
  config:
    server:
      DOMAIN: git.bapttf.com
      ROOT_URL: "https://git.bapttf.com/"
      SSH_DOMAIN: git.bapttf.com
      SSH_PORT: 22
      SSH_LISTEN_PORT: 22
    repository:
      USE_COMPAT_SSH_URI: false
