apiVersion: v1
kind: Service
metadata:
  name: infisical-redis
  namespace: infisical
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: infisical-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical-redis
  namespace: infisical
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: infisical-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: infisical-redis
    spec:
      containers:
      - name: redis
        image: redis:7.4-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
