apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwebui-cert
  namespace: openwebui
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "chat.bapttf.com"
