apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openwebui-infisical-secret
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /openwebui
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: openwebui-secret
      secretNamespace: openwebui
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openwebui-db-infisical-secret
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /openwebui/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: openwebui-db-secret
      secretNamespace: openwebui
      secretType: Opaque
      creationPolicy: Owner
