apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - openwebui-ingress.yaml

configMapGenerator:
  - name: openwebui-config
    literals:
      - DB_HOST=postgres-cluster-rw.cnpg-system.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=openwebui
