apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - certificate.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - ingressroute.yaml
