apiVersion: apps/v1
kind: Deployment
metadata:
  name: jujudb
  namespace: jujudb
  labels:
    app: jujudb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jujudb
  template:
    metadata:
      labels:
        app: jujudb
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: jujudb
          image: ghcr.io/bapttf/jujudb:0.1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: jujudb-config
            - secretRef:
                name: jujudb-secrets # Le secret généré par l'opérateur Infisical
            - secretRef:
                name: meilisearch-secrets