apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: jujudb-credentials
  namespace: jujudb
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # On s'assure que le secret est créé avant le déploiement
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /jujudb
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: jujudb-secrets # C'est le nom du secret Kubernetes qui sera généré
      secretNamespace: jujudb
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: jujudb-secrets
  namespace: jujudb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /meilisearch
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: meilisearch-secrets
      secretNamespace: jujudb
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-secrets
  namespace: jujudb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /github
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: ghcr-login-secret
      secretNamespace: jujudb
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner