# Tailscale Helm values
# https://tailscale.com/kb/1235/kubernetes-operator

# Namespace
namespace: tailscale

# Reference the Secret that will be synced from Infisical
# This is created by 01-tailscale-infisical-secret.yaml
secret: tailscale-credentials

# Enable the Kubernetes operator
operator:
  enabled: true
  replicaCount: 1

# Tailscale features
tailscale:
  features:
    routing: true
    exitNode: false
