apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: voyage-secrets
  namespace: voyage
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # On crée les secrets avant le déploiement
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /voyage # À créer dans Infisical
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: voyage-oauth-credentials
      secretNamespace: voyage
      secretType: Opaque
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: voyage-secrets
  namespace: voyage
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # On crée les secrets avant le déploiement
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /github # À créer dans Infisical
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: ghcr-login-secret
      secretNamespace: voyage
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner