apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dynamically pull and render the MinIO Helm Chart
helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0 # Reliable recent version
    namespace: minio
    releaseName: minio
    valuesFile: values.yaml

resources:
  - traefik-ingress.yaml
  - infisical-secret.yaml
  - tailscale-ingress.yaml