apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-s3-api
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
    # Matches your exact Garage compose regex
    - match: Host(`s3.192.168.122.133.nip.io`)
      kind: Rule
      services:
        - name: minio
          port: 9000
  tls: {}