apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hermes-lea-dashboard
  namespace: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hermes-lea.bapttf.com`)
      kind: Rule
      services:
        - name: hermes-lea
          port: 9119
  tls:
    secretName: hermes-lea-dashboard-tls-certificate
