apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - lldap-infisical-secret.yaml
  - configmap.yaml
  - lldap-deployment.yaml
  - lldap-service.yaml
  - lldap-tailscale-ingress.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
  - middleware.yaml
