apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cours-ia-cert
  namespace: openclaw
spec:
  secretName: cours-ia-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "cours-ia.bapttf.com"
