apiVersion: v1
kind: Service
metadata:
  name: openclaw-ssh
spec:
  publishNotReadyAddresses: true
  selector:
    app: openclaw
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
    - protocol: TCP
      port: 18800
      targetPort: 18800
      name: a2a
    - protocol: TCP
      port: 19000
      targetPort: 18789
      name: gateway
   