apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - litellm-deployment.yaml
  - litellm-service.yaml

configMapGenerator:
  - name: litellm-config
    files:
      - config.yaml=litellm_config.yaml