apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tripkit-cert
  namespace: tripkit
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "tripkit.bapttf.com"
