apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: system/argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
          - ServerSideApply=true