apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
      argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: system
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: system/cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
