# GitHub Actions Runner - base resources + AutoscalingRunnerSet
# Pure Kustomize (no Helm)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: system/github-actions-runner
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
