apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sshpiper-system
  namespace: sshpiper
spec:
  project: system
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: system/sshpiper
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
