apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 30.0.0
    helm:
      releaseName: traefik
      valueFiles:
        - https://raw.githubusercontent.com/BaptTF/vps-infra/main/workloads/traefik/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true