apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
      argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      targetRevision: 32.1.1
      chart: traefik
      helm:
        valueFiles:
          - $values/system/traefik/values.yaml
    - repoURL: https://github.com/BaptTF/vps-infra.git
      targetRevision: main                         
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true