apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-workload
  namespace: argocd
  annotations:
      argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: workloads/whoami
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true