apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: lacoope

resources:
  - infisical-secret.yaml
  - backend/infisical-secret.yaml
  - backend/certificate.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingressroute.yaml
  - frontend/certificate.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingressroute.yaml
