apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /argocd
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: argocd-webhook-secret
      secretNamespace: argocd
      secretType: Opaque
      creationPolicy: Owner