# system/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# 1. Render the official Helm Chart
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.4.10
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml

# 2. Add your custom Ingress manifests alongside it
resources:
  - certificate.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - namespace.yaml