# system/argocd/values.yaml
# Désactiver la Haute Disponibilité (comme le install.yaml)
redis-ha:
  enabled: false

# S'assurer que les composants annexes standards sont activés
dex:
  enabled: false

configs:
  cm:
    # This keeps your Kustomize Helm support enabled for OTHER apps
    kustomize.buildOptions: --enable-helm
    timeout.reconciliation: "600s"
  params:
    server.insecure: true
    reposerver.git.shallow.clone: "true"
    reposerver.parallelism.limit: "5"
    server.repo.server.timeout.seconds: "300"
    controller.repo.server.timeout.seconds: "300"
  secret:
    createSecret: false

repoServer:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  env:
    - name: ARGOCD_EXEC_TIMEOUT
      value: "5m"

server:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

applicationSet:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

notifications:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
