# system/argocd/values.yaml
# Désactiver la Haute Disponibilité (comme le install.yaml)
redis-ha:
  enabled: false

# Forcer l'utilisation du Redis standard
redis:
  enabled: true

# S'assurer que les composants annexes standards sont activés
dex:
  enabled: false
applicationSet:
  enabled: true
notifications:
  enabled: true

configs:
  cm:
    # This keeps your Kustomize Helm support enabled for OTHER apps
    kustomize.buildOptions: --enable-helm
    timeout.reconciliation: "600s"
  params:
    server.insecure: true
    reposerver.git.shallow.clone: "true"
    reposerver.parallelism.limit: "5"
    server.repo.server.timeout.seconds: "300"
    controller.repo.server.timeout.seconds: "300"

repoServer:
  env:
    - name: ARGOCD_EXEC_TIMEOUT
      value: "5m"
